# Generated by Django 2.2.16 on 2022-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220429_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=100, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'Модератор'), ('admin', 'Администратор'), ('user', 'Авторизованный пользователь')], default='user', max_length=10, verbose_name='Роль'),
        ),
    ]
